#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Overview
========
This program captures images from the camera, applies a Fourier transform,
and displays the transformed image alongside the original on the screen.

To run:
    $ python3 liveFT.py
For command-line options, use:
    $ python3 liveFT.py --help

press "q" to exit the application

Profile with:
    python -m cProfile -o LiveFT.prof LiveFT.py -i -c 2000 -r 1000
    snakeviz LiveFT.prof

Authors: Brian R. Pauw, I. Bressler with Codex support
Contact: brian@stack.nl
License: Apache-2.0
"""

import argparse
import math
import sys
import time
from functools import lru_cache
from typing import Tuple

import cv2
import numpy as np
from attrs import define, field, fields, validators

# Vectorize the math.erf function
erf_vectorized = np.vectorize(math.erf)

# typical video resolutions (from Ingos webcam), extend if needed, must be sorted
# used to find one which just covers the given columns&rows area
# on Linux generated by:
# v4l2-ctl --list-formats-ext | awk '/x/{split($3,a,"x"); print a[1]","a[2]}' \
#     | sort -h | uniq | awk '{ORS=", "; print "("$0")"}'
typRes = (
    (160, 90),
    (160, 120),
    (176, 144),
    (320, 180),
    (320, 240),
    (352, 288),
    (432, 240),
    (640, 360),
    (640, 480),
    (800, 448),
    (800, 600),
    (864, 480),
    (960, 720),
    (1024, 576),
    (1280, 720),
    (1600, 896),
    (1920, 1080),
    (2304, 1296),
    (2304, 1536),
)
lineSpacing = 40
MIN_FFT_GAMMA = 0.2
MAX_FFT_GAMMA = 5.0
FFT_GAMMA_STEP = 0.1


def normalizeUnit(frame: np.ndarray) -> np.ndarray:
    max_value = frame.max()
    if not np.isfinite(max_value) or max_value <= 0:
        return np.zeros_like(frame, dtype=np.float32)
    return frame / max_value


def limitFPS(
    next_frame_time: float,
    max_fps: float,
    time_fn=time.perf_counter,
    sleep_fn=time.sleep,
) -> float:
    now = time_fn()
    if max_fps <= 0:
        return now

    frame_interval = 1.0 / max_fps
    sleep_time = next_frame_time - now
    if sleep_time > 0:
        sleep_fn(sleep_time)
        now = time_fn()

    return max(next_frame_time + frame_interval, now)


@lru_cache(maxsize=16)
def getRadialProfileBins(shape: tuple[int, int]) -> tuple[np.ndarray, np.ndarray]:
    height, width = shape
    center_y = (height - 1) / 2.0
    center_x = (width - 1) / 2.0
    y_coords, x_coords = np.indices(shape, dtype=np.float32)
    radii = np.rint(np.sqrt((x_coords - center_x) ** 2 + (y_coords - center_y) ** 2)).astype(np.int32)
    radii_flat = radii.ravel()
    radial_counts = np.bincount(radii_flat)
    return radii_flat, radial_counts


def computeRadialProfile(image: np.ndarray) -> np.ndarray:
    if image.ndim != 2:
        raise ValueError("Radial profile expects a 2D image.")

    radii_flat, radial_counts = getRadialProfileBins(image.shape)
    image_flat = image.astype(np.float32, copy=False).ravel()
    radial_sums = np.bincount(radii_flat, weights=image_flat, minlength=radial_counts.size)
    profile = np.divide(
        radial_sums,
        radial_counts,
        out=np.zeros_like(radial_sums, dtype=np.float32),
        where=radial_counts > 0,
    )
    return profile.astype(np.float32, copy=False)


def applyGamma(image: np.ndarray, gamma: float) -> np.ndarray:
    if gamma <= 0:
        raise ValueError("Gamma must be greater than zero.")

    clipped = np.clip(image, 0.0, 1.0).astype(np.float32, copy=False)
    if gamma == 1.0:
        return clipped
    return np.power(clipped, gamma).astype(np.float32, copy=False)


def adjustGammaValue(current_gamma: float, delta: float) -> float:
    adjusted = current_gamma + delta
    return float(np.clip(adjusted, MIN_FFT_GAMMA, MAX_FFT_GAMMA))


def renderRadialProfile(profile: np.ndarray, width: int, height: int = 160) -> np.ndarray:
    panel = np.zeros((height, width), dtype=np.float32)
    if width <= 0 or height <= 0:
        return panel

    left_margin = 40
    right_margin = 16
    top_margin = 24
    bottom_margin = 24
    x_axis_y = height - bottom_margin
    x_axis_end = max(left_margin, width - right_margin - 1)
    plot_height = max(1, x_axis_y - top_margin)

    cv2.line(panel, (left_margin, top_margin), (left_margin, x_axis_y), 0.35, 1)
    cv2.line(panel, (left_margin, x_axis_y), (x_axis_end, x_axis_y), 0.35, 1)
    cv2.putText(panel, "Radial FFT", (left_margin, 16), cv2.FONT_HERSHEY_SIMPLEX, 0.5, 0.8, 1)

    if profile.size == 0:
        return panel

    profile_scaled = normalizeUnit(profile)
    x_positions = np.rint(np.linspace(left_margin, x_axis_end, num=profile.size)).astype(np.int32)
    y_positions = x_axis_y - np.rint(profile_scaled * plot_height).astype(np.int32)

    if profile.size == 1:
        cv2.circle(panel, (int(x_positions[0]), int(y_positions[0])), 1, 1.0, -1)
        return panel

    for start_x, start_y, end_x, end_y in zip(
        x_positions[:-1],
        y_positions[:-1],
        x_positions[1:],
        y_positions[1:],
    ):
        cv2.line(panel, (int(start_x), int(start_y)), (int(end_x), int(end_y)), 1.0, 1)

    return panel


def drawTextLine(frame: cv2.UMat, line_idx: int, text: str) -> None:
    posx, posy = 50, 50  # origin image coordinates
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.7
    color = (255, 255, 255)  # White color in BGR
    thickness = 2
    pos = (posx, posy + int(line_idx * lineSpacing * font_scale))
    cv2.putText(frame, text, pos, font, font_scale, color, thickness)


@define
class FrameProcessor:
    cropVertLo: int = field(default=0)
    cropVertUp: int = field(default=None)
    cropHorzLo: int = field(default=0)
    cropHorzUp: int = field(default=None)
    scaleVert: float = field(default=1.0)
    scaleHorz: float = field(default=1.0)
    killCenterLines: bool = field(default=False)
    taperWidth: float = field(default=0.2, validator=validators.and_(validators.ge(0.0), validators.le(1.0)))
    window: np.ndarray = field(default=None)  # error function window for input video frame

    def setWindow(self, w: int, h: int):
        # create a grid for an error function window
        x = np.linspace(-1.0, 1.0, w)
        y = np.linspace(-1.0, 1.0, h)
        x, y = np.meshgrid(x, y)
        # Create a window using the error function
        window_x = erf_vectorized((x + 1) / self.taperWidth) * erf_vectorized((1 - x) / self.taperWidth)
        window_y = erf_vectorized((y + 1) / self.taperWidth) * erf_vectorized((1 - y) / self.taperWidth)
        self.window = window_x * window_y

    def prepareFrame(self, frame: np.ndarray) -> np.ndarray:
        """Crop, scale, and normalize the captured frame."""
        # Crop the frame to the specified center region
        frame = frame[self.cropVertLo : self.cropVertUp, self.cropHorzLo : self.cropHorzUp]
        # Scale frame dimensions if necessary
        frame = cv2.resize(frame, None, fx=self.scaleHorz, fy=self.scaleVert)
        # make sure it's grayscale
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        return frame

    def applyWindow(self, frame: np.ndarray) -> np.ndarray:
        # Create a window using the error function
        if self.window is None:
            h, w = frame.shape
            self.setWindow(w, h)
        # Apply the window to the frame
        frame *= self.window
        frame -= frame.min()
        # expand range
        return normalizeUnit(frame)

    # static for use in test cases
    def computeFFT(self, frame: np.ndarray) -> np.ndarray:
        """Perform FFT on the frame, with optional line removal.
        Its declared static for easier (UI free) testing."""

        dft = cv2.dft(frame, flags=cv2.DFT_COMPLEX_OUTPUT)
        # Calculate magnitude spectrum (from complex)
        dft = dft[:, :, 0] ** 2 + dft[:, :, 1] ** 2
        # Shift the zero-frequency component to the center
        dft_shifted = np.fft.fftshift(dft)
        # Use log scale for better visualization
        fft_log = np.log1p(dft_shifted)

        # Optionally remove central lines to enhance dynamic range in display
        if self.killCenterLines:
            h, w = fft_log.shape[:2]
            fft_log[h // 2 - 1 : h // 2 + 1, :] = fft_log[h // 2 + 1 : h // 2 + 3, :]
            fft_log[:, w // 2 - 1 : w // 2 + 1] = fft_log[:, w // 2 + 1 : w // 2 + 3]

        # Normalize and convert back to NumPy array for display
        return normalizeUnit(fft_log)

    def __call__(self, frame) -> Tuple[np.ndarray]:
        """Process a single image with preparations resulting in the fourier transformed image.
        No assumptions should be made of the source, can be from camera or from disk."""
        frame = self.prepareFrame(frame)
        frame = self.applyWindow(frame)
        fft = self.computeFFT(frame)
        return frame, fft


@define
class LiveFT:
    """Handles live Fourier Transform display of camera feed."""

    # Core attributes with default values from command-line arguments
    # Note: This order affects parse_args() below, all attrs until device become cmdline args
    numShots: int = field(
        default=int(1e5), metadata={"help": "Max number of images before program exits", "short": "n"}
    )
    # numBins: int = field(default=200, metadata={"help": "Number of integration bins", "short": "N"})
    # nContrIms: int = field(default=30, metadata={"help": "Average contrast over N images", "short": "o"})
    camDevice: int = field(default=0, metadata={"help": "Camera device ID", "short": "d"})
    imAvgs: int = field(default=1, metadata={"help": "Average N images for display and FFT", "short": "a"})
    vScale: float = field(default=1.2, metadata={"help": "Vertical video scale", "short": "y"})
    hScale: float = field(default=1.2, metadata={"help": "Horizontal video scale", "short": "x"})
    killCenterLines: bool = field(default=False, metadata={"help": "Remove central lines from FFT image", "short": "k"})
    figid: str = field(
        default="liveFFT by Brian R. Pauw - press 'h' for help, 'q' to exit.",
        metadata={"help": "Image window name", "short": "f"},
    )
    rows: int = field(default=500, metadata={"help": "Use center N rows of video", "short": "r"})
    columns: int = field(default=500, metadata={"help": "Use center N columns of video", "short": "c"})
    showInfo: bool = field(default=False, metadata={"help": "Show FPS info text overlay", "short": "i"})
    showRadialProfile: bool = field(
        default=False,
        metadata={"help": "Show FFT radial distribution panel", "short": "o"},
    )
    fftGamma: float = field(
        default=1.0,
        validator=validators.gt(0.0),
        metadata={"help": "Display gamma for the FFT image", "short": "e"},
    )
    maxFPS: float = field(
        default=0.0,
        validator=validators.ge(0.0),
        metadata={"help": "Limit processing speed to N FPS (0 disables limit)", "short": "m"},
    )
    frameTimeCount: int = field(
        default=10, metadata={"help": "Number of frames to average frame time by", "short": "t"}
    )

    # Derived attributes initialized post-instantiation
    vc: cv2.VideoCapture = field(init=False, validator=validators.instance_of(cv2.VideoCapture))
    optionsInteractive: Tuple[str] = field(default=("showHelp", "showInfo", "showRadialProfile", "killCenterLines"))
    lastDisplayShape: tuple[int, int] | None = field(init=False, default=None)
    frameTime: np.ndarray = field(init=False)  # array for moving average of frame calc. time
    frameProc: FrameProcessor = field(factory=FrameProcessor)

    # not an attribute available as cmdline argument
    showHelp: bool = field(default=False, metadata={"help": "Show interactive help text", "short": "h"})

    def __attrs_post_init__(self) -> None:
        """Initialize video capture and plotting after attribute setup."""

        # Open camera device
        self.vc = cv2.VideoCapture(self.camDevice)
        if not self.vc.isOpened():
            raise ValueError("Could not open video device.")
        # Set desired resolution based on desired colums & rows
        res = [(w, h) for w, h in typRes if w >= self.columns and h >= self.rows]
        res = res[0] if res else typRes[-1]  # pick the largest if none was found
        self.vc.set(cv2.CAP_PROP_FRAME_WIDTH, res[0])
        self.vc.set(cv2.CAP_PROP_FRAME_HEIGHT, res[1])
        # Set the codec to MJPEG which much faster often
        fourcc = cv2.VideoWriter_fourcc(*"MJPG")
        self.vc.set(cv2.CAP_PROP_FOURCC, fourcc)
        # change the desired fps of the video source
        desired_fps = 240  # typically lower, limited by camera driver support
        self.vc.set(cv2.CAP_PROP_FPS, desired_fps)

        # Initialize display window
        cv2.namedWindow(self.figid, cv2.WINDOW_GUI_NORMAL | cv2.WINDOW_NORMAL)
        cv2.resizeWindow(self.figid, 1024, 768)

        self.frameTime = np.zeros(self.frameTimeCount)
        # Start main loop for capturing and processing frames
        self.run()

    def drawInfoText(self, frame, infoData) -> None:
        drawTextLine(frame, 0, ", ".join([f"{k}: {v}" for k, v in infoData.items()]))
        # show the current camera resolution
        actual_width = int(self.vc.get(cv2.CAP_PROP_FRAME_WIDTH))
        actual_height = int(self.vc.get(cv2.CAP_PROP_FRAME_HEIGHT))
        # show the video stream format as well
        video_text = f"{actual_width}x{actual_height}"
        fourcc = int(self.vc.get(cv2.CAP_PROP_FOURCC))
        if fourcc > 31:
            video_text += "@" + fourcc.to_bytes(4, byteorder=sys.byteorder).decode()
        drawTextLine(frame, 1, f"(Input: {video_text})")

    def drawHelpText(self, frame) -> None:
        """Draws a static help text into the frame."""
        lineOffset = 3
        drawTextLine(frame, lineOffset, "Help | press key:")
        help_items = [
            (attr.metadata["short"], attr.metadata["help"])
            for attr in fields(type(self))
            if attr.name in self.optionsInteractive
        ]
        help_items.append(("+/-", "Adjust FFT gamma"))
        for index, (shortcut, help_text) in enumerate(help_items):
            drawTextLine(frame, lineOffset + index + 1, f"{shortcut}-> {help_text}")

    def toggleShortOption(self, key) -> None:
        for a in fields(type(self)):
            if a.name not in self.optionsInteractive:
                continue
            if key & 0xFF == ord(a.metadata["short"]):
                setattr(self, a.name, not getattr(self, a.name))

    def adjustGamma(self, delta: float) -> None:
        updated_gamma = adjustGammaValue(self.fftGamma, delta)
        if updated_gamma != self.fftGamma:
            self.fftGamma = updated_gamma
            print(f"FFT gamma: {self.fftGamma:.2f}")

    def handleInteractiveKey(self, key) -> None:
        self.toggleShortOption(key)

        keycode = key & 0xFF
        if keycode in {ord("+"), ord("=")}:
            self.adjustGamma(FFT_GAMMA_STEP)
        elif keycode in {ord("-"), ord("_")}:
            self.adjustGamma(-FFT_GAMMA_STEP)

    def run(self) -> None:
        """Main loop to capture and process frames from the camera."""
        num_frames = 0
        frames_counted = 0
        start_time = time.time()  # for calculating FPS including capturing
        infoData = {"#Frame": 0, "fps": "", "hw": "cpu"}
        next_frame_time = time.perf_counter()
        while num_frames < self.numShots:
            next_frame_time = limitFPS(next_frame_time, self.maxFPS)
            num_frames += 1

            # Capture key press to close window (e.g., 'q' key)
            key = cv2.waitKey(1)
            if key & 0xFF == ord("q"):
                print("Exiting on user request.")
                break
            self.handleInteractiveKey(key)

            # Check if the window is still open, break if closed
            if not cv2.getWindowProperty(self.figid, cv2.WND_PROP_VISIBLE):
                print("Window closed by user.")
                break

            frame_final = self.composeFrame(num_frames, infoData)
            # gather some info
            elapsed = time.time() - start_time
            fps = (num_frames - frames_counted) / elapsed
            if elapsed > 2:  # duration of FPS measurement window
                start_time = time.time()
                frames_counted = num_frames

            # Show info text on request
            if self.showInfo:
                infoData["gamma"] = f"{self.fftGamma:.2f}"
                if self.maxFPS > 0:
                    infoData["fps limit"] = f"{self.maxFPS:.2f}"
                else:
                    infoData.pop("fps limit", None)
                infoData.update({"#Frame": num_frames, "fps": f"{fps:.2f}"})
                self.drawInfoText(frame_final, infoData)
            if self.showHelp:
                self.drawHelpText(frame_final)

            if frame_final.size:  # show the frame if there is any
                frame_shape = frame_final.shape[:2]
                if self.lastDisplayShape != frame_shape:
                    frame_height, frame_width = frame_shape
                    cv2.resizeWindow(self.figid, frame_width, frame_height)
                    self.lastDisplayShape = frame_shape
                cv2.imshow(self.figid, frame_final)

        self.vc.release()
        cv2.destroyAllWindows()

    def captureFrame(self) -> np.ndarray:
        """Capture, process, and display a single frame."""
        frame = None
        nframes = 0
        while nframes < self.imAvgs:
            success, iframe = self.vc.read()
            if not success:
                raise ValueError("Failed to capture frame.")
                # return np.array([])
            if frame is None:
                frame = iframe.astype(np.float32)
            else:
                frame += iframe.astype(np.float32)
            nframes += 1
        if self.imAvgs > 1:  # average images possibly
            frame /= self.imAvgs
        return frame

    def composeFrame(self, frameIdx: int, infoData: dict) -> np.ndarray:
        frame = self.captureFrame()
        frame_time = time.time()  # calculation time of a single frame, without capturing

        # Ensure crop dimensions are within frame limits
        height, width = frame.shape[:2]
        if self.rows > height:
            self.rows = height
        if self.columns > width:
            self.columns = width
        # Configure cropping boundaries for the center region of the frame.
        self.frameProc.cropVertLo = height // 2 - self.rows // 2
        self.frameProc.cropVertUp = height // 2 + self.rows // 2
        self.frameProc.cropHorzLo = width // 2 - self.columns // 2
        self.frameProc.cropHorzUp = width // 2 + self.columns // 2
        # forward the desired scaling
        self.frameProc.scaleHorz = self.hScale
        self.frameProc.scaleVert = self.vScale
        # forward options for the fourier transformed result
        self.frameProc.killCenterLines = self.killCenterLines
        frame, fft = self.frameProc(frame)
        fft_display = applyGamma(fft, self.fftGamma)

        # normalize and convert to numpy array
        framesCombined = np.concatenate((frame, fft_display), axis=1)
        if self.showRadialProfile:
            profile = computeRadialProfile(fft)
            radial_height = max(120, frame.shape[0] // 3)
            radial_panel = renderRadialProfile(profile, framesCombined.shape[1], height=radial_height)
            framesCombined = np.concatenate((framesCombined, radial_panel), axis=0)

        # record how long this frame took to process
        self.frameTime[frameIdx % self.frameTime.size] = time.time() - frame_time
        # show the frame time average for info overlay
        infoData["frame time"] = f"{self.frameTime.mean() * 1e3:.1f} ms"
        return framesCombined


# Function to parse arguments for the script
def parse_args(liveftCls: type[LiveFT]) -> argparse.Namespace:
    """Parses command-line arguments.
    Uses the LiveFT class for some options configuration."""
    parser = argparse.ArgumentParser(description="Live Fourier Transform of camera feed.")
    for attr in liveftCls.__attrs_attrs__:
        if attr.name == "vc":
            break
        # print(f"{attr=}") # class config for debugging
        pkwargs = dict(help=attr.metadata["help"])
        if attr.type is bool:
            pkwargs["action"] = "store_true" if not attr.default else "store_false"
        else:
            pkwargs.update(type=attr.type, default=attr.default)
        # print(f"{pkwargs}") # show parser config for debugging
        parser.add_argument("-" + attr.metadata["short"], "--" + attr.name, **pkwargs)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args(LiveFT)
    live_ft = LiveFT(**vars(args))
